# -*- coding: utf-8 -*-
"""YOLO11_Scan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RA8ovEtW0BquqTFfEDYQ32I4FpQQcZQS
"""

!pip install ultralytics

import ultralytics
ultralytics.checks()

!mkdir -p /content/drive/MyDrive/Colab_files/wind_turbine_yolo_train

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab_files/wind_turbine_yolo_train

!unzip windturbine_yolov11.zip -d /content/drive/MyDrive/Colab_files/wind_turbine_yolo_train

!yolo train model=/content/drive/MyDrive/Colab_files/wind_turbine_yolo_train/yolo11l.pt data=/content/drive/MyDrive/Colab_files/wind_turbine_yolo_train/data.yaml epochs=60 imgsz=640 device=0

from google.colab import drive
drive.mount('/content/drive')